import multiprocessing
from scraper import GoogleMapsScraper
from tqdm import tqdm

def run_scraper_with_tqdm(config, index, tqdm_position):
    """
    Runs a scraper instance and passes a unique tqdm position.
    """
    print(f"Starting scraper {index}...")
    scraper = GoogleMapsScraper(config=config)
    scraper.scrape(position=tqdm_position)  # Pass the tqdm position to avoid overlap

def main():
    # Configurations for each scraper
    configs_list = [
        {
            "countries": ["Nederland"],
            "places": [
                    "Groningen", "Centrum", "Oud-Zuid", "Oud-West", "Oud-Noord", "Oosterparkwijk", "Helpman e.o.", "Nieuw-West",
                    "Noordwest", "Noordoost", "Noorddijk e.o.", "Almere", "Stadskanaal", "Stadskanaal", "Veendam", "Wijk 00 Veendam-kern",
                    "Zeewolde", "Wijk 00", "Achtkarspelen", "Harlingen", "Wijk 00 Harlingen", "Heerenveen", "Wijk 01 Heerenveen", "Leeuwarden",
                    "Oud-Oost", "Ooststellingwerf", "Opsterland", "Smallingerland", "Weststellingwerf", "Assen", "Coevorden", "Wijk 10 Coevorden",
                    "Emmen", "Hoogeveen", "Wijk 50 Hoogeveen", "Meppel", "Almelo", "Borne", "Wijk 00 Borne", "Dalfsen",
                    "Deventer", "Enschede", "Wijk 00 Binnensingelgebied", "Wijk 02 Boswinkel - Stadsveld", "Wijk 04 Enschede-Noord", "Wijk 06 Enschede-Zuid", "Wijk 08 Glanerbrug en omgeving", "Haaksbergen",
                    "Wijk 00 Haaksbergen (dorp)", "Hardenberg", "Hardenberg", "Hellendoorn", "Hengelo (O.)", "Kampen", "Kampen", "Losser",
                    "Noordoostpolder", "Wijk 01 Emmeloord", "Oldenzaal", "Ommen", "Raalte", "Raalte", "Tubbergen", "Urk",
                    "Wijk 00 Urk", "Wierden", "Zwolle", "Wijk 22 Stadshagen", "Aalten", "Apeldoorn", "West", "Zuid",
                    "Zuidoost", "Oost", "Noordoost", "Arnhem", "Barneveld", "Wijk 54 Barneveld", "Beuningen", "Beuningen",
                    "Brummen", "Buren", "Culemborg", "Culemborg Oost", "Doetinchem", "Druten", "Duiven", "Ede",
                    "Ede-West", "Elburg", "Epe", "Wijk 00 Epe", "Ermelo", "Schil rondom het centrum", "Harderwijk", "Heerde",
                    "Heumen", "Lochem", "Maasdriel", "Nijkerk", "Nijkerk-stad", "Nijmegen", "Nijmegen-Oost", "Nijmegen-Oud-West",
                    "Nijmegen-Nieuw-West", "Nijmegen-Midden", "Nijmegen-Zuid", "Dukenburg", "Nijmegen-Noord", "Oldebroek", "Putten", "Wijk 00 Putten",
                    "Renkum", "Rheden", "Wijk 00 Dieren", "Wijk 02 Velp", "Tiel", "Tiel kern", "Voorst", "Wijk 01 Twello-Nijbroek",
                    "Wageningen", "Winterswijk", "Wijk 00 Stad", "Wijchen", "Wijk 01 Wijchen kern", "Zaltbommel", "Zevenaar", "Zevenaar",
                    "Zutphen", "Nunspeet", "Wijk 00 Nunspeet", "Dronten", "Amersfoort", "Baarn", "De Bilt", "Bunschoten",
                    "Wijk 00", "Houten", "Leusden", "Rhenen", "Soest", "Utrecht", "Wijk 01 West", "Wijk 02 Noordwest",
                    "Wijk 03 Overvecht", "Wijk 04 Noordoost", "Wijk 05 Oost", "Wijk 06 Binnenstad", "Wijk 07 Zuid", "Wijk 08 Zuidwest", "Wijk 09 Leidsche Rijn", "Wijk 10 Vleuten-De Meern",
                    "Veenendaal", "Wijk bij Duurstede", "Wijk 00 Wijk bij Duurstede", "IJsselstein", "Wijk 00 IJsselstein", "Zeist", "Zeist Centrum", "Zeist-Noord",
                    "Nieuwegein", "Aalsmeer", "Alkmaar", "Zuid", "De Mare", "Amstelveen", "Amsterdam", "Jordaan",
                    "Oostelijke Eilanden/Kadijken", "Landlust", "Staatsliedenbuurt", "Geuzenveld", "Osdorp-Oost", "Westlandgracht", "Museumkwartier", "Oude Pijp",
                    "Nieuwe Pijp", "Scheldebuurt", "Buitenveldert-West", "Oostelijk Havengebied", "Frankendael", "Middenmeer", "Bergen (NH.)", "Beverwijk",
                    "Bloemendaal", "Castricum", "Diemen", "Edam-Volendam", "Wijk 02 Volendam", "Enkhuizen", "Haarlem", "Oude Stad",
                    "Haarlemmermeer", "Hoofddorp", "Nieuw-Vennep", "Heemskerk", "Heemstede", "Wijk 00 Heemstede-Centrum", "Heiloo", "Den Helder",
                    "Hilversum", "Zuid", "Oost", "Hoorn", "Wijk 33 Kersenboogerd-Zuid", "Huizen", "Medemblik", "Purmerend",
                    "Wijk 02 Overwhere", "Wijk 07 Weidevenne", "Schagen", "Texel", "Uithoorn", "Velsen", "Zandvoort", "Zaanstad",
                    "Alblasserdam", "Alphen aan den Rijn", "Kerk en Zanen", "Boskoop", "Barendrecht", "Drechterland", "Capelle aan den IJssel", "Delft",
                    "Wijk 11 Binnenstad", "Wijk 24 Voorhof", "Wijk 25 Buitenhof", "Wijk 28 Wippolder", "Dordrecht", "Wijk 09 Sterrenburg", "Wijk 11 Stadspolders", "Gorinchem",
                    "Gouda", "'s-Gravenhage", "Wijk 04 Benoordenhout", "Wijk 07 Scheveningen", "Wijk 09 Geuzen- en Statenkwartier", "Wijk 12 Bomen- en Bloemenbuurt", "Wijk 17 Loosduinen", "Wijk 18 Waldeck",
                    "Wijk 20 Valkenboskwartier", "Wijk 21 Regentessekwartier", "Wijk 25 Mariahoeve en Marlot", "Wijk 26 Bezuidenhout", "Wijk 27 Stationsbuurt", "Wijk 28 Centrum", "Wijk 29 Schildersbuurt", "Wijk 31 Rustenburg en Oostbroek",
                    "Wijk 32 Leyenburg", "Wijk 33 Bouwlust", "Wijk 34 Morgenstond", "Wijk 36 Moerwijk", "Wijk 38 Laakkwartier en Spoorwijk", "Wijk 40 Wateringse Veld", "Wijk 42 Ypenburg", "Wijk 44 Leidschenveen",
                    "Hardinxveld-Giessendam", "Hendrik-Ido-Ambacht", "Stede Broec", "Hillegom", "Katwijk", "Katwijk aan Zee", "Rijnsburg", "Krimpen aan den IJssel",
                    "Wijk 00 Krimpen aan den IJssel", "Leiden", "Binnenstad-Noord", "Leiden-Noord", "Roodenburgerdistrict", "Bos- en Gasthuisdistrict", "Leiderdorp", "Wijk 00",
                    "Lisse", "Maassluis", "Nieuwkoop", "Noordwijk", "Noordwijk Binnen", "Oegstgeest", "Papendrecht", "Ridderkerk",
                    "Rotterdam", "Rotterdam Centrum", "Delfshaven", "Overschie", "Noord", "Hillegersberg-Schiebroek", "Kralingen-Crooswijk", "Feijenoord",
                    "IJsselmonde", "Prins Alexander", "Charlois", "Hoogvliet", "Rijswijk (ZH.)", "Schiedam", "Wijk 06 Nieuwland", "Sliedrecht",
                    "Albrandswaard", "Vlaardingen", "Centrum", "Voorschoten", "Wijk 00", "Waddinxveen", "Wassenaar", "Wijk 01 Noordoostelijk deel der gemeente",
                    "Woerden", "Wijk 01 Woerden-Midden", "Zoetermeer", "Centrum", "Meerzicht", "Buytenwegh de Leyens", "Seghwaert", "Rokkeveen",
                    "Oosterheem", "Zwijndrecht", "Borsele", "Goes", "Wijk 01 Goes", "West Maas en Waal", "Hulst", "Middelburg (Z.)",
                    "Reimerswaal", "Terneuzen", "Tholen", "Veere", "Vlissingen", "De Ronde Venen", "Mijdrecht", "Tytsjerksteradiel",
                    "Asten", "Bergen op Zoom", "Wijk 00 Bergen op Zoom-Oude stad en omgeving", "Wijk 02 Bergen op Zoom-Oost", "Best", "Wijk 00 Best", "Boxtel", "Wijk 00 Boxtel",
                    "Breda", "Breda centrum", "Breda noord", "Breda oost", "Breda zuid-oost", "Breda west", "Breda noord-west", "Deurne",
                    "Dongen", "Dongen", "Eersel", "Eindhoven", "Putten", "Erp", "Ontginning", "Aanschot",
                    "Oud-Strijp", "Oud-Gestel", "Etten-Leur", "Noord woongebied", "Geertruidenberg", "Gilze en Rijen", "Rijen", "Goirle",
                    "Helmond", "Wijk 10 Binnenstad", "'s-Hertogenbosch", "Binnenstad", "Zuidoost", "Graafsepoort", "Noord", "Maaspoort",
                    "West", "Heusden", "Wijk 01 Drunen", "Wijk 05 Vlijmen", "Hilvarenbeek", "Loon op Zand", "Nuenen, Gerwen en Nederwetten", "Wijk 00 Nuenen",
                    "Oirschot", "Oisterwijk", "Oosterhout", "Oss", "Rucphen", "Sint-Michielsgestel", "Someren", "Son en Breugel",
                    "Steenbergen", "Waterland", "Tilburg", "Valkenswaard", "Wijk 00 Valkenswaard", "Veldhoven", "Wijk 00 Veldhoven", "Vught",
                    "Waalre", "Wijk 00 Waalre", "Waalwijk", "Waalwijk", "Woensdrecht", "Zundert", "Wormerland", "Landgraaf",
                    "Wijk 00 Schaesberg", "Beek (L.)", "Brunssum", "Gennep", "Heerlen", "Kerkrade", "Wijk 00 Kerkrade-West", "Wijk 01 Kerkrade-Oost",
                    "Maastricht", "Wijk 00 Centrum", "Wijk 02 Buitenwijk West", "Wijk 04 Buitenwijk Oost", "Wijk 06 Buitenwijk Zuidoost", "Meerssen", "Nederweert", "Roermond",
                    "Stein (L.)", "Venlo", "Venray", "Weert", "Valkenburg aan de Geul", "Lelystad", "Horst aan de Maas", "Oude IJsselstreek",
                    "Teylingen", "Utrechtse Heuvelrug", "Driebergen", "Oost Gelre", "Koggenland", "Lansingerland", "Leudal", "Maasgouw",
                    "Gemert-Bakel", "Halderberge", "Heeze-Leende", "Laarbeek", "Roerdalen", "Roosendaal", "Schouwen-Duiveland", "Aa en Hunze",
                    "Borger-Odoorn", "De Wolden", "Wijdemeren", "Noordenveld", "Wijk 00 Roden", "Twenterand", "Westerveld", "Lingewaard",
                    "Huissen", "Cranendonck", "Steenwijkerland", "Steenwijk", "Moerdijk", "Wijk 00 Zevenbergen", "Echt-Susteren", "Sluis",
                    "Drimmelen", "Bernheze", "Bergeijk", "Bladel", "Gulpen-Wittem", "Tynaarlo", "Midden-Drenthe", "Overbetuwe",
                    "Hof van Twente", "Neder-Betuwe", "Rijssen-Holten", "Geldrop-Mierlo", "Geldrop", "Olst-Wijhe", "Dinkelland", "Westland",
                    "Wijk 01 Naaldwijk", "Wijk 04 's-Gravenzande", "Midden-Delfland", "Berkelland", "Bronckhorst", "Sittard-Geleen", "Wijk 01 Sittard", "Wijk 02 Overhoven",
                    "Wijk 05 Geleen", "Kaag en Braassem", "Dantumadiel", "Zuidplas", "Nieuwerkerk aan den IJssel wijk 04", "Peel en Maas", "Oldambt", "Wijk 00 Winschoten",
                    "Zwartewaterland", "S�dwest-Frysl�n", "Wijk 01 Sneek", "Bodegraven-Reeuwijk", "Eijsden-Margraten", "Stichtse Vecht", "Wijk 01 Maarssen", "Wijk 12 Maarssenbroek",
                    "Hollands Kroon", "Leidschendam-Voorburg", "Goeree-Overflakkee", "Pijnacker-Nootdorp", "Pijnacker", "Nootdorp", "Nissewaard", "Krimpenerwaard",
                    "De Fryske Marren", "Gooise Meren", "Naarden", "Berg en Dal", "Meierijstad", "Schijndel", "Sint-Oedenrode", "Veghel",
                    "Waadhoeke", "Westerwolde", "Midden-Groningen", "Beekdaelen", "Montferland", "Wijk 02 Didam", "Altena", "West Betuwe",
                    "Vijfheerenlanden", "Hoeksche Waard", "Oud-Beijerland", "Het Hogeland", "Westerkwartier", "Noardeast-Frysl�n", "Molenlanden", "Eemsdelta",
                    "Dijk en Waard", "Land van Cuijk", "Cuijk", "Maashorst", "Uden", "Voorne aan Zee"
                ],
            "keywords": [
                "Marketing Agency",
                ]
        },
        {
            "countries": ["Nederland"],
            "places": [
                    "Groningen", "Centrum", "Oud-Zuid", "Oud-West", "Oud-Noord", "Oosterparkwijk", "Helpman e.o.", "Nieuw-West",
                    "Noordwest", "Noordoost", "Noorddijk e.o.", "Almere", "Stadskanaal", "Stadskanaal", "Veendam", "Wijk 00 Veendam-kern",
                    "Zeewolde", "Wijk 00", "Achtkarspelen", "Harlingen", "Wijk 00 Harlingen", "Heerenveen", "Wijk 01 Heerenveen", "Leeuwarden",
                    "Oud-Oost", "Ooststellingwerf", "Opsterland", "Smallingerland", "Weststellingwerf", "Assen", "Coevorden", "Wijk 10 Coevorden",
                    "Emmen", "Hoogeveen", "Wijk 50 Hoogeveen", "Meppel", "Almelo", "Borne", "Wijk 00 Borne", "Dalfsen",
                    "Deventer", "Enschede", "Wijk 00 Binnensingelgebied", "Wijk 02 Boswinkel - Stadsveld", "Wijk 04 Enschede-Noord", "Wijk 06 Enschede-Zuid", "Wijk 08 Glanerbrug en omgeving", "Haaksbergen",
                    "Wijk 00 Haaksbergen (dorp)", "Hardenberg", "Hardenberg", "Hellendoorn", "Hengelo (O.)", "Kampen", "Kampen", "Losser",
                    "Noordoostpolder", "Wijk 01 Emmeloord", "Oldenzaal", "Ommen", "Raalte", "Raalte", "Tubbergen", "Urk",
                    "Wijk 00 Urk", "Wierden", "Zwolle", "Wijk 22 Stadshagen", "Aalten", "Apeldoorn", "West", "Zuid",
                    "Zuidoost", "Oost", "Noordoost", "Arnhem", "Barneveld", "Wijk 54 Barneveld", "Beuningen", "Beuningen",
                    "Brummen", "Buren", "Culemborg", "Culemborg Oost", "Doetinchem", "Druten", "Duiven", "Ede",
                    "Ede-West", "Elburg", "Epe", "Wijk 00 Epe", "Ermelo", "Schil rondom het centrum", "Harderwijk", "Heerde",
                    "Heumen", "Lochem", "Maasdriel", "Nijkerk", "Nijkerk-stad", "Nijmegen", "Nijmegen-Oost", "Nijmegen-Oud-West",
                    "Nijmegen-Nieuw-West", "Nijmegen-Midden", "Nijmegen-Zuid", "Dukenburg", "Nijmegen-Noord", "Oldebroek", "Putten", "Wijk 00 Putten",
                    "Renkum", "Rheden", "Wijk 00 Dieren", "Wijk 02 Velp", "Tiel", "Tiel kern", "Voorst", "Wijk 01 Twello-Nijbroek",
                    "Wageningen", "Winterswijk", "Wijk 00 Stad", "Wijchen", "Wijk 01 Wijchen kern", "Zaltbommel", "Zevenaar", "Zevenaar",
                    "Zutphen", "Nunspeet", "Wijk 00 Nunspeet", "Dronten", "Amersfoort", "Baarn", "De Bilt", "Bunschoten",
                    "Wijk 00", "Houten", "Leusden", "Rhenen", "Soest", "Utrecht", "Wijk 01 West", "Wijk 02 Noordwest",
                    "Wijk 03 Overvecht", "Wijk 04 Noordoost", "Wijk 05 Oost", "Wijk 06 Binnenstad", "Wijk 07 Zuid", "Wijk 08 Zuidwest", "Wijk 09 Leidsche Rijn", "Wijk 10 Vleuten-De Meern",
                    "Veenendaal", "Wijk bij Duurstede", "Wijk 00 Wijk bij Duurstede", "IJsselstein", "Wijk 00 IJsselstein", "Zeist", "Zeist Centrum", "Zeist-Noord",
                    "Nieuwegein", "Aalsmeer", "Alkmaar", "Zuid", "De Mare", "Amstelveen", "Amsterdam", "Jordaan",
                    "Oostelijke Eilanden/Kadijken", "Landlust", "Staatsliedenbuurt", "Geuzenveld", "Osdorp-Oost", "Westlandgracht", "Museumkwartier", "Oude Pijp",
                    "Nieuwe Pijp", "Scheldebuurt", "Buitenveldert-West", "Oostelijk Havengebied", "Frankendael", "Middenmeer", "Bergen (NH.)", "Beverwijk",
                    "Bloemendaal", "Castricum", "Diemen", "Edam-Volendam", "Wijk 02 Volendam", "Enkhuizen", "Haarlem", "Oude Stad",
                    "Haarlemmermeer", "Hoofddorp", "Nieuw-Vennep", "Heemskerk", "Heemstede", "Wijk 00 Heemstede-Centrum", "Heiloo", "Den Helder",
                    "Hilversum", "Zuid", "Oost", "Hoorn", "Wijk 33 Kersenboogerd-Zuid", "Huizen", "Medemblik", "Purmerend",
                    "Wijk 02 Overwhere", "Wijk 07 Weidevenne", "Schagen", "Texel", "Uithoorn", "Velsen", "Zandvoort", "Zaanstad",
                    "Alblasserdam", "Alphen aan den Rijn", "Kerk en Zanen", "Boskoop", "Barendrecht", "Drechterland", "Capelle aan den IJssel", "Delft",
                    "Wijk 11 Binnenstad", "Wijk 24 Voorhof", "Wijk 25 Buitenhof", "Wijk 28 Wippolder", "Dordrecht", "Wijk 09 Sterrenburg", "Wijk 11 Stadspolders", "Gorinchem",
                    "Gouda", "'s-Gravenhage", "Wijk 04 Benoordenhout", "Wijk 07 Scheveningen", "Wijk 09 Geuzen- en Statenkwartier", "Wijk 12 Bomen- en Bloemenbuurt", "Wijk 17 Loosduinen", "Wijk 18 Waldeck",
                    "Wijk 20 Valkenboskwartier", "Wijk 21 Regentessekwartier", "Wijk 25 Mariahoeve en Marlot", "Wijk 26 Bezuidenhout", "Wijk 27 Stationsbuurt", "Wijk 28 Centrum", "Wijk 29 Schildersbuurt", "Wijk 31 Rustenburg en Oostbroek",
                    "Wijk 32 Leyenburg", "Wijk 33 Bouwlust", "Wijk 34 Morgenstond", "Wijk 36 Moerwijk", "Wijk 38 Laakkwartier en Spoorwijk", "Wijk 40 Wateringse Veld", "Wijk 42 Ypenburg", "Wijk 44 Leidschenveen",
                    "Hardinxveld-Giessendam", "Hendrik-Ido-Ambacht", "Stede Broec", "Hillegom", "Katwijk", "Katwijk aan Zee", "Rijnsburg", "Krimpen aan den IJssel",
                    "Wijk 00 Krimpen aan den IJssel", "Leiden", "Binnenstad-Noord", "Leiden-Noord", "Roodenburgerdistrict", "Bos- en Gasthuisdistrict", "Leiderdorp", "Wijk 00",
                    "Lisse", "Maassluis", "Nieuwkoop", "Noordwijk", "Noordwijk Binnen", "Oegstgeest", "Papendrecht", "Ridderkerk",
                    "Rotterdam", "Rotterdam Centrum", "Delfshaven", "Overschie", "Noord", "Hillegersberg-Schiebroek", "Kralingen-Crooswijk", "Feijenoord",
                    "IJsselmonde", "Prins Alexander", "Charlois", "Hoogvliet", "Rijswijk (ZH.)", "Schiedam", "Wijk 06 Nieuwland", "Sliedrecht",
                    "Albrandswaard", "Vlaardingen", "Centrum", "Voorschoten", "Wijk 00", "Waddinxveen", "Wassenaar", "Wijk 01 Noordoostelijk deel der gemeente",
                    "Woerden", "Wijk 01 Woerden-Midden", "Zoetermeer", "Centrum", "Meerzicht", "Buytenwegh de Leyens", "Seghwaert", "Rokkeveen",
                    "Oosterheem", "Zwijndrecht", "Borsele", "Goes", "Wijk 01 Goes", "West Maas en Waal", "Hulst", "Middelburg (Z.)",
                    "Reimerswaal", "Terneuzen", "Tholen", "Veere", "Vlissingen", "De Ronde Venen", "Mijdrecht", "Tytsjerksteradiel",
                    "Asten", "Bergen op Zoom", "Wijk 00 Bergen op Zoom-Oude stad en omgeving", "Wijk 02 Bergen op Zoom-Oost", "Best", "Wijk 00 Best", "Boxtel", "Wijk 00 Boxtel",
                    "Breda", "Breda centrum", "Breda noord", "Breda oost", "Breda zuid-oost", "Breda west", "Breda noord-west", "Deurne",
                    "Dongen", "Dongen", "Eersel", "Eindhoven", "Putten", "Erp", "Ontginning", "Aanschot",
                    "Oud-Strijp", "Oud-Gestel", "Etten-Leur", "Noord woongebied", "Geertruidenberg", "Gilze en Rijen", "Rijen", "Goirle",
                    "Helmond", "Wijk 10 Binnenstad", "'s-Hertogenbosch", "Binnenstad", "Zuidoost", "Graafsepoort", "Noord", "Maaspoort",
                    "West", "Heusden", "Wijk 01 Drunen", "Wijk 05 Vlijmen", "Hilvarenbeek", "Loon op Zand", "Nuenen, Gerwen en Nederwetten", "Wijk 00 Nuenen",
                    "Oirschot", "Oisterwijk", "Oosterhout", "Oss", "Rucphen", "Sint-Michielsgestel", "Someren", "Son en Breugel",
                    "Steenbergen", "Waterland", "Tilburg", "Valkenswaard", "Wijk 00 Valkenswaard", "Veldhoven", "Wijk 00 Veldhoven", "Vught",
                    "Waalre", "Wijk 00 Waalre", "Waalwijk", "Waalwijk", "Woensdrecht", "Zundert", "Wormerland", "Landgraaf",
                    "Wijk 00 Schaesberg", "Beek (L.)", "Brunssum", "Gennep", "Heerlen", "Kerkrade", "Wijk 00 Kerkrade-West", "Wijk 01 Kerkrade-Oost",
                    "Maastricht", "Wijk 00 Centrum", "Wijk 02 Buitenwijk West", "Wijk 04 Buitenwijk Oost", "Wijk 06 Buitenwijk Zuidoost", "Meerssen", "Nederweert", "Roermond",
                    "Stein (L.)", "Venlo", "Venray", "Weert", "Valkenburg aan de Geul", "Lelystad", "Horst aan de Maas", "Oude IJsselstreek",
                    "Teylingen", "Utrechtse Heuvelrug", "Driebergen", "Oost Gelre", "Koggenland", "Lansingerland", "Leudal", "Maasgouw",
                    "Gemert-Bakel", "Halderberge", "Heeze-Leende", "Laarbeek", "Roerdalen", "Roosendaal", "Schouwen-Duiveland", "Aa en Hunze",
                    "Borger-Odoorn", "De Wolden", "Wijdemeren", "Noordenveld", "Wijk 00 Roden", "Twenterand", "Westerveld", "Lingewaard",
                    "Huissen", "Cranendonck", "Steenwijkerland", "Steenwijk", "Moerdijk", "Wijk 00 Zevenbergen", "Echt-Susteren", "Sluis",
                    "Drimmelen", "Bernheze", "Bergeijk", "Bladel", "Gulpen-Wittem", "Tynaarlo", "Midden-Drenthe", "Overbetuwe",
                    "Hof van Twente", "Neder-Betuwe", "Rijssen-Holten", "Geldrop-Mierlo", "Geldrop", "Olst-Wijhe", "Dinkelland", "Westland",
                    "Wijk 01 Naaldwijk", "Wijk 04 's-Gravenzande", "Midden-Delfland", "Berkelland", "Bronckhorst", "Sittard-Geleen", "Wijk 01 Sittard", "Wijk 02 Overhoven",
                    "Wijk 05 Geleen", "Kaag en Braassem", "Dantumadiel", "Zuidplas", "Nieuwerkerk aan den IJssel wijk 04", "Peel en Maas", "Oldambt", "Wijk 00 Winschoten",
                    "Zwartewaterland", "S�dwest-Frysl�n", "Wijk 01 Sneek", "Bodegraven-Reeuwijk", "Eijsden-Margraten", "Stichtse Vecht", "Wijk 01 Maarssen", "Wijk 12 Maarssenbroek",
                    "Hollands Kroon", "Leidschendam-Voorburg", "Goeree-Overflakkee", "Pijnacker-Nootdorp", "Pijnacker", "Nootdorp", "Nissewaard", "Krimpenerwaard",
                    "De Fryske Marren", "Gooise Meren", "Naarden", "Berg en Dal", "Meierijstad", "Schijndel", "Sint-Oedenrode", "Veghel",
                    "Waadhoeke", "Westerwolde", "Midden-Groningen", "Beekdaelen", "Montferland", "Wijk 02 Didam", "Altena", "West Betuwe",
                    "Vijfheerenlanden", "Hoeksche Waard", "Oud-Beijerland", "Het Hogeland", "Westerkwartier", "Noardeast-Frysl�n", "Molenlanden", "Eemsdelta",
                    "Dijk en Waard", "Land van Cuijk", "Cuijk", "Maashorst", "Uden", "Voorne aan Zee"
                ],
            "keywords": [
                "Advertising Agency",
                ]
        },
        {
            "countries": ["Nederland"],
            "places": [
                    "Groningen", "Centrum", "Oud-Zuid", "Oud-West", "Oud-Noord", "Oosterparkwijk", "Helpman e.o.", "Nieuw-West",
                    "Noordwest", "Noordoost", "Noorddijk e.o.", "Almere", "Stadskanaal", "Stadskanaal", "Veendam", "Wijk 00 Veendam-kern",
                    "Zeewolde", "Wijk 00", "Achtkarspelen", "Harlingen", "Wijk 00 Harlingen", "Heerenveen", "Wijk 01 Heerenveen", "Leeuwarden",
                    "Oud-Oost", "Ooststellingwerf", "Opsterland", "Smallingerland", "Weststellingwerf", "Assen", "Coevorden", "Wijk 10 Coevorden",
                    "Emmen", "Hoogeveen", "Wijk 50 Hoogeveen", "Meppel", "Almelo", "Borne", "Wijk 00 Borne", "Dalfsen",
                    "Deventer", "Enschede", "Wijk 00 Binnensingelgebied", "Wijk 02 Boswinkel - Stadsveld", "Wijk 04 Enschede-Noord", "Wijk 06 Enschede-Zuid", "Wijk 08 Glanerbrug en omgeving", "Haaksbergen",
                    "Wijk 00 Haaksbergen (dorp)", "Hardenberg", "Hardenberg", "Hellendoorn", "Hengelo (O.)", "Kampen", "Kampen", "Losser",
                    "Noordoostpolder", "Wijk 01 Emmeloord", "Oldenzaal", "Ommen", "Raalte", "Raalte", "Tubbergen", "Urk",
                    "Wijk 00 Urk", "Wierden", "Zwolle", "Wijk 22 Stadshagen", "Aalten", "Apeldoorn", "West", "Zuid",
                    "Zuidoost", "Oost", "Noordoost", "Arnhem", "Barneveld", "Wijk 54 Barneveld", "Beuningen", "Beuningen",
                    "Brummen", "Buren", "Culemborg", "Culemborg Oost", "Doetinchem", "Druten", "Duiven", "Ede",
                    "Ede-West", "Elburg", "Epe", "Wijk 00 Epe", "Ermelo", "Schil rondom het centrum", "Harderwijk", "Heerde",
                    "Heumen", "Lochem", "Maasdriel", "Nijkerk", "Nijkerk-stad", "Nijmegen", "Nijmegen-Oost", "Nijmegen-Oud-West",
                    "Nijmegen-Nieuw-West", "Nijmegen-Midden", "Nijmegen-Zuid", "Dukenburg", "Nijmegen-Noord", "Oldebroek", "Putten", "Wijk 00 Putten",
                    "Renkum", "Rheden", "Wijk 00 Dieren", "Wijk 02 Velp", "Tiel", "Tiel kern", "Voorst", "Wijk 01 Twello-Nijbroek",
                    "Wageningen", "Winterswijk", "Wijk 00 Stad", "Wijchen", "Wijk 01 Wijchen kern", "Zaltbommel", "Zevenaar", "Zevenaar",
                    "Zutphen", "Nunspeet", "Wijk 00 Nunspeet", "Dronten", "Amersfoort", "Baarn", "De Bilt", "Bunschoten",
                    "Wijk 00", "Houten", "Leusden", "Rhenen", "Soest", "Utrecht", "Wijk 01 West", "Wijk 02 Noordwest",
                    "Wijk 03 Overvecht", "Wijk 04 Noordoost", "Wijk 05 Oost", "Wijk 06 Binnenstad", "Wijk 07 Zuid", "Wijk 08 Zuidwest", "Wijk 09 Leidsche Rijn", "Wijk 10 Vleuten-De Meern",
                    "Veenendaal", "Wijk bij Duurstede", "Wijk 00 Wijk bij Duurstede", "IJsselstein", "Wijk 00 IJsselstein", "Zeist", "Zeist Centrum", "Zeist-Noord",
                    "Nieuwegein", "Aalsmeer", "Alkmaar", "Zuid", "De Mare", "Amstelveen", "Amsterdam", "Jordaan",
                    "Oostelijke Eilanden/Kadijken", "Landlust", "Staatsliedenbuurt", "Geuzenveld", "Osdorp-Oost", "Westlandgracht", "Museumkwartier", "Oude Pijp",
                    "Nieuwe Pijp", "Scheldebuurt", "Buitenveldert-West", "Oostelijk Havengebied", "Frankendael", "Middenmeer", "Bergen (NH.)", "Beverwijk",
                    "Bloemendaal", "Castricum", "Diemen", "Edam-Volendam", "Wijk 02 Volendam", "Enkhuizen", "Haarlem", "Oude Stad",
                    "Haarlemmermeer", "Hoofddorp", "Nieuw-Vennep", "Heemskerk", "Heemstede", "Wijk 00 Heemstede-Centrum", "Heiloo", "Den Helder",
                    "Hilversum", "Zuid", "Oost", "Hoorn", "Wijk 33 Kersenboogerd-Zuid", "Huizen", "Medemblik", "Purmerend",
                    "Wijk 02 Overwhere", "Wijk 07 Weidevenne", "Schagen", "Texel", "Uithoorn", "Velsen", "Zandvoort", "Zaanstad",
                    "Alblasserdam", "Alphen aan den Rijn", "Kerk en Zanen", "Boskoop", "Barendrecht", "Drechterland", "Capelle aan den IJssel", "Delft",
                    "Wijk 11 Binnenstad", "Wijk 24 Voorhof", "Wijk 25 Buitenhof", "Wijk 28 Wippolder", "Dordrecht", "Wijk 09 Sterrenburg", "Wijk 11 Stadspolders", "Gorinchem",
                    "Gouda", "'s-Gravenhage", "Wijk 04 Benoordenhout", "Wijk 07 Scheveningen", "Wijk 09 Geuzen- en Statenkwartier", "Wijk 12 Bomen- en Bloemenbuurt", "Wijk 17 Loosduinen", "Wijk 18 Waldeck",
                    "Wijk 20 Valkenboskwartier", "Wijk 21 Regentessekwartier", "Wijk 25 Mariahoeve en Marlot", "Wijk 26 Bezuidenhout", "Wijk 27 Stationsbuurt", "Wijk 28 Centrum", "Wijk 29 Schildersbuurt", "Wijk 31 Rustenburg en Oostbroek",
                    "Wijk 32 Leyenburg", "Wijk 33 Bouwlust", "Wijk 34 Morgenstond", "Wijk 36 Moerwijk", "Wijk 38 Laakkwartier en Spoorwijk", "Wijk 40 Wateringse Veld", "Wijk 42 Ypenburg", "Wijk 44 Leidschenveen",
                    "Hardinxveld-Giessendam", "Hendrik-Ido-Ambacht", "Stede Broec", "Hillegom", "Katwijk", "Katwijk aan Zee", "Rijnsburg", "Krimpen aan den IJssel",
                    "Wijk 00 Krimpen aan den IJssel", "Leiden", "Binnenstad-Noord", "Leiden-Noord", "Roodenburgerdistrict", "Bos- en Gasthuisdistrict", "Leiderdorp", "Wijk 00",
                    "Lisse", "Maassluis", "Nieuwkoop", "Noordwijk", "Noordwijk Binnen", "Oegstgeest", "Papendrecht", "Ridderkerk",
                    "Rotterdam", "Rotterdam Centrum", "Delfshaven", "Overschie", "Noord", "Hillegersberg-Schiebroek", "Kralingen-Crooswijk", "Feijenoord",
                    "IJsselmonde", "Prins Alexander", "Charlois", "Hoogvliet", "Rijswijk (ZH.)", "Schiedam", "Wijk 06 Nieuwland", "Sliedrecht",
                    "Albrandswaard", "Vlaardingen", "Centrum", "Voorschoten", "Wijk 00", "Waddinxveen", "Wassenaar", "Wijk 01 Noordoostelijk deel der gemeente",
                    "Woerden", "Wijk 01 Woerden-Midden", "Zoetermeer", "Centrum", "Meerzicht", "Buytenwegh de Leyens", "Seghwaert", "Rokkeveen",
                    "Oosterheem", "Zwijndrecht", "Borsele", "Goes", "Wijk 01 Goes", "West Maas en Waal", "Hulst", "Middelburg (Z.)",
                    "Reimerswaal", "Terneuzen", "Tholen", "Veere", "Vlissingen", "De Ronde Venen", "Mijdrecht", "Tytsjerksteradiel",
                    "Asten", "Bergen op Zoom", "Wijk 00 Bergen op Zoom-Oude stad en omgeving", "Wijk 02 Bergen op Zoom-Oost", "Best", "Wijk 00 Best", "Boxtel", "Wijk 00 Boxtel",
                    "Breda", "Breda centrum", "Breda noord", "Breda oost", "Breda zuid-oost", "Breda west", "Breda noord-west", "Deurne",
                    "Dongen", "Dongen", "Eersel", "Eindhoven", "Putten", "Erp", "Ontginning", "Aanschot",
                    "Oud-Strijp", "Oud-Gestel", "Etten-Leur", "Noord woongebied", "Geertruidenberg", "Gilze en Rijen", "Rijen", "Goirle",
                    "Helmond", "Wijk 10 Binnenstad", "'s-Hertogenbosch", "Binnenstad", "Zuidoost", "Graafsepoort", "Noord", "Maaspoort",
                    "West", "Heusden", "Wijk 01 Drunen", "Wijk 05 Vlijmen", "Hilvarenbeek", "Loon op Zand", "Nuenen, Gerwen en Nederwetten", "Wijk 00 Nuenen",
                    "Oirschot", "Oisterwijk", "Oosterhout", "Oss", "Rucphen", "Sint-Michielsgestel", "Someren", "Son en Breugel",
                    "Steenbergen", "Waterland", "Tilburg", "Valkenswaard", "Wijk 00 Valkenswaard", "Veldhoven", "Wijk 00 Veldhoven", "Vught",
                    "Waalre", "Wijk 00 Waalre", "Waalwijk", "Waalwijk", "Woensdrecht", "Zundert", "Wormerland", "Landgraaf",
                    "Wijk 00 Schaesberg", "Beek (L.)", "Brunssum", "Gennep", "Heerlen", "Kerkrade", "Wijk 00 Kerkrade-West", "Wijk 01 Kerkrade-Oost",
                    "Maastricht", "Wijk 00 Centrum", "Wijk 02 Buitenwijk West", "Wijk 04 Buitenwijk Oost", "Wijk 06 Buitenwijk Zuidoost", "Meerssen", "Nederweert", "Roermond",
                    "Stein (L.)", "Venlo", "Venray", "Weert", "Valkenburg aan de Geul", "Lelystad", "Horst aan de Maas", "Oude IJsselstreek",
                    "Teylingen", "Utrechtse Heuvelrug", "Driebergen", "Oost Gelre", "Koggenland", "Lansingerland", "Leudal", "Maasgouw",
                    "Gemert-Bakel", "Halderberge", "Heeze-Leende", "Laarbeek", "Roerdalen", "Roosendaal", "Schouwen-Duiveland", "Aa en Hunze",
                    "Borger-Odoorn", "De Wolden", "Wijdemeren", "Noordenveld", "Wijk 00 Roden", "Twenterand", "Westerveld", "Lingewaard",
                    "Huissen", "Cranendonck", "Steenwijkerland", "Steenwijk", "Moerdijk", "Wijk 00 Zevenbergen", "Echt-Susteren", "Sluis",
                    "Drimmelen", "Bernheze", "Bergeijk", "Bladel", "Gulpen-Wittem", "Tynaarlo", "Midden-Drenthe", "Overbetuwe",
                    "Hof van Twente", "Neder-Betuwe", "Rijssen-Holten", "Geldrop-Mierlo", "Geldrop", "Olst-Wijhe", "Dinkelland", "Westland",
                    "Wijk 01 Naaldwijk", "Wijk 04 's-Gravenzande", "Midden-Delfland", "Berkelland", "Bronckhorst", "Sittard-Geleen", "Wijk 01 Sittard", "Wijk 02 Overhoven",
                    "Wijk 05 Geleen", "Kaag en Braassem", "Dantumadiel", "Zuidplas", "Nieuwerkerk aan den IJssel wijk 04", "Peel en Maas", "Oldambt", "Wijk 00 Winschoten",
                    "Zwartewaterland", "S�dwest-Frysl�n", "Wijk 01 Sneek", "Bodegraven-Reeuwijk", "Eijsden-Margraten", "Stichtse Vecht", "Wijk 01 Maarssen", "Wijk 12 Maarssenbroek",
                    "Hollands Kroon", "Leidschendam-Voorburg", "Goeree-Overflakkee", "Pijnacker-Nootdorp", "Pijnacker", "Nootdorp", "Nissewaard", "Krimpenerwaard",
                    "De Fryske Marren", "Gooise Meren", "Naarden", "Berg en Dal", "Meierijstad", "Schijndel", "Sint-Oedenrode", "Veghel",
                    "Waadhoeke", "Westerwolde", "Midden-Groningen", "Beekdaelen", "Montferland", "Wijk 02 Didam", "Altena", "West Betuwe",
                    "Vijfheerenlanden", "Hoeksche Waard", "Oud-Beijerland", "Het Hogeland", "Westerkwartier", "Noardeast-Frysl�n", "Molenlanden", "Eemsdelta",
                    "Dijk en Waard", "Land van Cuijk", "Cuijk", "Maashorst", "Uden", "Voorne aan Zee"
                ],
            "keywords": [
                "Digital Marketing",
                ]
        },
        {
            "countries": ["Nederland"],
            "places": [
                    "Groningen", "Centrum", "Oud-Zuid", "Oud-West", "Oud-Noord", "Oosterparkwijk", "Helpman e.o.", "Nieuw-West",
                    "Noordwest", "Noordoost", "Noorddijk e.o.", "Almere", "Stadskanaal", "Stadskanaal", "Veendam", "Wijk 00 Veendam-kern",
                    "Zeewolde", "Wijk 00", "Achtkarspelen", "Harlingen", "Wijk 00 Harlingen", "Heerenveen", "Wijk 01 Heerenveen", "Leeuwarden",
                    "Oud-Oost", "Ooststellingwerf", "Opsterland", "Smallingerland", "Weststellingwerf", "Assen", "Coevorden", "Wijk 10 Coevorden",
                    "Emmen", "Hoogeveen", "Wijk 50 Hoogeveen", "Meppel", "Almelo", "Borne", "Wijk 00 Borne", "Dalfsen",
                    "Deventer", "Enschede", "Wijk 00 Binnensingelgebied", "Wijk 02 Boswinkel - Stadsveld", "Wijk 04 Enschede-Noord", "Wijk 06 Enschede-Zuid", "Wijk 08 Glanerbrug en omgeving", "Haaksbergen",
                    "Wijk 00 Haaksbergen (dorp)", "Hardenberg", "Hardenberg", "Hellendoorn", "Hengelo (O.)", "Kampen", "Kampen", "Losser",
                    "Noordoostpolder", "Wijk 01 Emmeloord", "Oldenzaal", "Ommen", "Raalte", "Raalte", "Tubbergen", "Urk",
                    "Wijk 00 Urk", "Wierden", "Zwolle", "Wijk 22 Stadshagen", "Aalten", "Apeldoorn", "West", "Zuid",
                    "Zuidoost", "Oost", "Noordoost", "Arnhem", "Barneveld", "Wijk 54 Barneveld", "Beuningen", "Beuningen",
                    "Brummen", "Buren", "Culemborg", "Culemborg Oost", "Doetinchem", "Druten", "Duiven", "Ede",
                    "Ede-West", "Elburg", "Epe", "Wijk 00 Epe", "Ermelo", "Schil rondom het centrum", "Harderwijk", "Heerde",
                    "Heumen", "Lochem", "Maasdriel", "Nijkerk", "Nijkerk-stad", "Nijmegen", "Nijmegen-Oost", "Nijmegen-Oud-West",
                    "Nijmegen-Nieuw-West", "Nijmegen-Midden", "Nijmegen-Zuid", "Dukenburg", "Nijmegen-Noord", "Oldebroek", "Putten", "Wijk 00 Putten",
                    "Renkum", "Rheden", "Wijk 00 Dieren", "Wijk 02 Velp", "Tiel", "Tiel kern", "Voorst", "Wijk 01 Twello-Nijbroek",
                    "Wageningen", "Winterswijk", "Wijk 00 Stad", "Wijchen", "Wijk 01 Wijchen kern", "Zaltbommel", "Zevenaar", "Zevenaar",
                    "Zutphen", "Nunspeet", "Wijk 00 Nunspeet", "Dronten", "Amersfoort", "Baarn", "De Bilt", "Bunschoten",
                    "Wijk 00", "Houten", "Leusden", "Rhenen", "Soest", "Utrecht", "Wijk 01 West", "Wijk 02 Noordwest",
                    "Wijk 03 Overvecht", "Wijk 04 Noordoost", "Wijk 05 Oost", "Wijk 06 Binnenstad", "Wijk 07 Zuid", "Wijk 08 Zuidwest", "Wijk 09 Leidsche Rijn", "Wijk 10 Vleuten-De Meern",
                    "Veenendaal", "Wijk bij Duurstede", "Wijk 00 Wijk bij Duurstede", "IJsselstein", "Wijk 00 IJsselstein", "Zeist", "Zeist Centrum", "Zeist-Noord",
                    "Nieuwegein", "Aalsmeer", "Alkmaar", "Zuid", "De Mare", "Amstelveen", "Amsterdam", "Jordaan",
                    "Oostelijke Eilanden/Kadijken", "Landlust", "Staatsliedenbuurt", "Geuzenveld", "Osdorp-Oost", "Westlandgracht", "Museumkwartier", "Oude Pijp",
                    "Nieuwe Pijp", "Scheldebuurt", "Buitenveldert-West", "Oostelijk Havengebied", "Frankendael", "Middenmeer", "Bergen (NH.)", "Beverwijk",
                    "Bloemendaal", "Castricum", "Diemen", "Edam-Volendam", "Wijk 02 Volendam", "Enkhuizen", "Haarlem", "Oude Stad",
                    "Haarlemmermeer", "Hoofddorp", "Nieuw-Vennep", "Heemskerk", "Heemstede", "Wijk 00 Heemstede-Centrum", "Heiloo", "Den Helder",
                    "Hilversum", "Zuid", "Oost", "Hoorn", "Wijk 33 Kersenboogerd-Zuid", "Huizen", "Medemblik", "Purmerend",
                    "Wijk 02 Overwhere", "Wijk 07 Weidevenne", "Schagen", "Texel", "Uithoorn", "Velsen", "Zandvoort", "Zaanstad",
                    "Alblasserdam", "Alphen aan den Rijn", "Kerk en Zanen", "Boskoop", "Barendrecht", "Drechterland", "Capelle aan den IJssel", "Delft",
                    "Wijk 11 Binnenstad", "Wijk 24 Voorhof", "Wijk 25 Buitenhof", "Wijk 28 Wippolder", "Dordrecht", "Wijk 09 Sterrenburg", "Wijk 11 Stadspolders", "Gorinchem",
                    "Gouda", "'s-Gravenhage", "Wijk 04 Benoordenhout", "Wijk 07 Scheveningen", "Wijk 09 Geuzen- en Statenkwartier", "Wijk 12 Bomen- en Bloemenbuurt", "Wijk 17 Loosduinen", "Wijk 18 Waldeck",
                    "Wijk 20 Valkenboskwartier", "Wijk 21 Regentessekwartier", "Wijk 25 Mariahoeve en Marlot", "Wijk 26 Bezuidenhout", "Wijk 27 Stationsbuurt", "Wijk 28 Centrum", "Wijk 29 Schildersbuurt", "Wijk 31 Rustenburg en Oostbroek",
                    "Wijk 32 Leyenburg", "Wijk 33 Bouwlust", "Wijk 34 Morgenstond", "Wijk 36 Moerwijk", "Wijk 38 Laakkwartier en Spoorwijk", "Wijk 40 Wateringse Veld", "Wijk 42 Ypenburg", "Wijk 44 Leidschenveen",
                    "Hardinxveld-Giessendam", "Hendrik-Ido-Ambacht", "Stede Broec", "Hillegom", "Katwijk", "Katwijk aan Zee", "Rijnsburg", "Krimpen aan den IJssel",
                    "Wijk 00 Krimpen aan den IJssel", "Leiden", "Binnenstad-Noord", "Leiden-Noord", "Roodenburgerdistrict", "Bos- en Gasthuisdistrict", "Leiderdorp", "Wijk 00",
                    "Lisse", "Maassluis", "Nieuwkoop", "Noordwijk", "Noordwijk Binnen", "Oegstgeest", "Papendrecht", "Ridderkerk",
                    "Rotterdam", "Rotterdam Centrum", "Delfshaven", "Overschie", "Noord", "Hillegersberg-Schiebroek", "Kralingen-Crooswijk", "Feijenoord",
                    "IJsselmonde", "Prins Alexander", "Charlois", "Hoogvliet", "Rijswijk (ZH.)", "Schiedam", "Wijk 06 Nieuwland", "Sliedrecht",
                    "Albrandswaard", "Vlaardingen", "Centrum", "Voorschoten", "Wijk 00", "Waddinxveen", "Wassenaar", "Wijk 01 Noordoostelijk deel der gemeente",
                    "Woerden", "Wijk 01 Woerden-Midden", "Zoetermeer", "Centrum", "Meerzicht", "Buytenwegh de Leyens", "Seghwaert", "Rokkeveen",
                    "Oosterheem", "Zwijndrecht", "Borsele", "Goes", "Wijk 01 Goes", "West Maas en Waal", "Hulst", "Middelburg (Z.)",
                    "Reimerswaal", "Terneuzen", "Tholen", "Veere", "Vlissingen", "De Ronde Venen", "Mijdrecht", "Tytsjerksteradiel",
                    "Asten", "Bergen op Zoom", "Wijk 00 Bergen op Zoom-Oude stad en omgeving", "Wijk 02 Bergen op Zoom-Oost", "Best", "Wijk 00 Best", "Boxtel", "Wijk 00 Boxtel",
                    "Breda", "Breda centrum", "Breda noord", "Breda oost", "Breda zuid-oost", "Breda west", "Breda noord-west", "Deurne",
                    "Dongen", "Dongen", "Eersel", "Eindhoven", "Putten", "Erp", "Ontginning", "Aanschot",
                    "Oud-Strijp", "Oud-Gestel", "Etten-Leur", "Noord woongebied", "Geertruidenberg", "Gilze en Rijen", "Rijen", "Goirle",
                    "Helmond", "Wijk 10 Binnenstad", "'s-Hertogenbosch", "Binnenstad", "Zuidoost", "Graafsepoort", "Noord", "Maaspoort",
                    "West", "Heusden", "Wijk 01 Drunen", "Wijk 05 Vlijmen", "Hilvarenbeek", "Loon op Zand", "Nuenen, Gerwen en Nederwetten", "Wijk 00 Nuenen",
                    "Oirschot", "Oisterwijk", "Oosterhout", "Oss", "Rucphen", "Sint-Michielsgestel", "Someren", "Son en Breugel",
                    "Steenbergen", "Waterland", "Tilburg", "Valkenswaard", "Wijk 00 Valkenswaard", "Veldhoven", "Wijk 00 Veldhoven", "Vught",
                    "Waalre", "Wijk 00 Waalre", "Waalwijk", "Waalwijk", "Woensdrecht", "Zundert", "Wormerland", "Landgraaf",
                    "Wijk 00 Schaesberg", "Beek (L.)", "Brunssum", "Gennep", "Heerlen", "Kerkrade", "Wijk 00 Kerkrade-West", "Wijk 01 Kerkrade-Oost",
                    "Maastricht", "Wijk 00 Centrum", "Wijk 02 Buitenwijk West", "Wijk 04 Buitenwijk Oost", "Wijk 06 Buitenwijk Zuidoost", "Meerssen", "Nederweert", "Roermond",
                    "Stein (L.)", "Venlo", "Venray", "Weert", "Valkenburg aan de Geul", "Lelystad", "Horst aan de Maas", "Oude IJsselstreek",
                    "Teylingen", "Utrechtse Heuvelrug", "Driebergen", "Oost Gelre", "Koggenland", "Lansingerland", "Leudal", "Maasgouw",
                    "Gemert-Bakel", "Halderberge", "Heeze-Leende", "Laarbeek", "Roerdalen", "Roosendaal", "Schouwen-Duiveland", "Aa en Hunze",
                    "Borger-Odoorn", "De Wolden", "Wijdemeren", "Noordenveld", "Wijk 00 Roden", "Twenterand", "Westerveld", "Lingewaard",
                    "Huissen", "Cranendonck", "Steenwijkerland", "Steenwijk", "Moerdijk", "Wijk 00 Zevenbergen", "Echt-Susteren", "Sluis",
                    "Drimmelen", "Bernheze", "Bergeijk", "Bladel", "Gulpen-Wittem", "Tynaarlo", "Midden-Drenthe", "Overbetuwe",
                    "Hof van Twente", "Neder-Betuwe", "Rijssen-Holten", "Geldrop-Mierlo", "Geldrop", "Olst-Wijhe", "Dinkelland", "Westland",
                    "Wijk 01 Naaldwijk", "Wijk 04 's-Gravenzande", "Midden-Delfland", "Berkelland", "Bronckhorst", "Sittard-Geleen", "Wijk 01 Sittard", "Wijk 02 Overhoven",
                    "Wijk 05 Geleen", "Kaag en Braassem", "Dantumadiel", "Zuidplas", "Nieuwerkerk aan den IJssel wijk 04", "Peel en Maas", "Oldambt", "Wijk 00 Winschoten",
                    "Zwartewaterland", "S�dwest-Frysl�n", "Wijk 01 Sneek", "Bodegraven-Reeuwijk", "Eijsden-Margraten", "Stichtse Vecht", "Wijk 01 Maarssen", "Wijk 12 Maarssenbroek",
                    "Hollands Kroon", "Leidschendam-Voorburg", "Goeree-Overflakkee", "Pijnacker-Nootdorp", "Pijnacker", "Nootdorp", "Nissewaard", "Krimpenerwaard",
                    "De Fryske Marren", "Gooise Meren", "Naarden", "Berg en Dal", "Meierijstad", "Schijndel", "Sint-Oedenrode", "Veghel",
                    "Waadhoeke", "Westerwolde", "Midden-Groningen", "Beekdaelen", "Montferland", "Wijk 02 Didam", "Altena", "West Betuwe",
                    "Vijfheerenlanden", "Hoeksche Waard", "Oud-Beijerland", "Het Hogeland", "Westerkwartier", "Noardeast-Frysl�n", "Molenlanden", "Eemsdelta",
                    "Dijk en Waard", "Land van Cuijk", "Cuijk", "Maashorst", "Uden", "Voorne aan Zee"
                ],
            "keywords": [
                "Event Planner",
                ]
        },
    ]

    # Function to run scrapers in parallel
    processes = []
    for i, config in enumerate(configs_list):
        process = multiprocessing.Process(
            target=run_scraper_with_tqdm,
            args=(config, i, i)  # Pass config, index, and tqdm position
        )
        processes.append(process)

    # Start all processes
    for process in processes:
        process.start()

    # Wait for all processes to complete
    for process in processes:
        process.join()

    print("All scrapers have completed.")

if __name__ == "__main__":
    main()
